name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run compile-web
        npm run package-web

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@4fa655aad48f56911cad16db9252399a9e592848
      #uses: browser-actions/setup-chrome@v0.0.0

    - name: Test
      run: |
        npm run pretest
        npm run test
